// POSTS ACTIONS
export const FETCH_POST = 'FETCH_POSTS';
export const ADD_LIKE = 'ADD_LIKE';
export const DELETE_LIKE = 'DELETE_LIKE';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const GET_POST = 'GET_POST';
export const CLEAR_POST = 'CLEAR_POST';
export const ADD_COMMENT = 'ADD_COMMENT';

// LOADING ACTIONS
export const START_PAGE_LOADING = 'START_PAGE_LOADING';
export const STOP_PAGE_LOADING = 'STOP_PAGE_LOADING';
export const START_COMPONENT_LOADING = 'START_COMPONENT_LOADING';
export const STOP_COMPONENT_LOADING = 'STOP_COMPONENT_LOADING';

// USER ACTIONS
export const AUTHENTICATE = 'AUTHENTICATE';
export const REHYDRATE_USER = 'persist/REHYDRATE';
export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const LOGOUT = 'LOGOUT';
export const ADD_FOLLOWING = 'ADD_FOLLOWING';
export const DELETE_FOLLOWING = 'DELETE_FOLLOWING';
export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';

// PROFILE ACTIONS
export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';
export const ADD_FOLLOWER = 'ADD_FOLLOWER';
export const DELETE_FOLLOWER = 'DELETE_FOLLOWER';

// TOASTS ACTIONS
export const ADD_TOAST = 'ADD_TOAST';
export const DELETE_TOAST = 'DELETE_TOAST';
