// POSTS ACTIONS
export const FETCH_POST = 'FETCH_POSTS';
export const ADD_LIKE = 'ADD_LIKE';
export const DELETE_LIKE = 'DELETE_LIKE';

// LOADING ACTIONS
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const START_LOADING_FORM = 'START_LOADING_FORM';
export const STOP_LOADING_FORM = 'STOP_LOADING_FORM';

// USER ACTIONS
export const AUTHENTICATE = 'AUTHENTICATE';
export const REHYDRATE_USER = 'persist/REHYDRATE';
